---

- name: Include OS family specific vars
  with_first_found:
    - "../vars/os-families/{{ ansible_os_family }}.yml"
    - ../vars/os-families/default.yml
  include_vars: "{{ item }}"

- name: Install dependencies
  become: true
  package:
    name: "{{ intellij_dependencies }}"
    state: present

- name: Create IntelliJ IDEA installation directory
  become: true
  file:
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
    dest: "{{ intellij_install_dir }}"

- name: Install IntelliJ IDEA
  become: true
  unarchive:
    src: "{{ intellij_download_dir }}/{{ intellij_package_filename }}"
    remote_src: true
    extra_opts: '--strip-components=1'
    dest: "{{ intellij_install_dir }}"
    owner: root
    group: root
    mode: 'o-w'
    creates: "{{ intellij_install_dir }}/bin"

- name: Create bin link
  become: true
  file:
    src: "{{ intellij_install_dir }}/bin/idea.sh"
    dest: /usr/local/bin/idea
    state: link
    owner: root
    group: root
    mode: 'u=rwx,go=rx'

- name: Install IntelliJ IDEA desktop file
  become: true
  template:
    src: jetbrains-idea.desktop.j2
    dest: "/usr/share/applications/{{ intellij_desktop_filename }}"
    owner: root
    group: root
    mode: 'u=rw,go=r'
