---
platforms:
  - name: centos7-${CI_JOB_ID:-0}
    image: code.europa.eu:4567/ecgalaxy/centos7-ansible:latest
    pre_build_image: true
    environment:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
  - name: rockylinux8-${CI_JOB_ID:-0}
    image: code.europa.eu:4567/ecgalaxy/rockylinux8-ansible:latest
    pre_build_image: true
    environment:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
