---
platforms:
  - name: centos7-${CI_JOB_ID:-0}
    image: geerlingguy/docker-centos7-ansible:latest
    pre_build_image: true
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
  - name: rockylinux8-${CI_JOB_ID:-0}
    image: geerlingguy/docker-rockylinux8-ansible:latest
    pre_build_image: true
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
