---

- name: Include role defaults vars
  with_first_found:
    - "../../../../defaults/main.yml"
  include_vars: "{{ item }}"

- name: Load edition vars
  include_vars: '../../../../vars/editions/{{ intellij_edition }}.yml'

- name: "Get stat '{{ intellij_install_dir }}'"
  stat:
    path: "{{ intellij_install_dir }}"
  register: directory
 
- name: "Assert that Intellij installation dir is present"
  assert:
    that:
      - "directory.stat.exists"
      - "directory.stat.isdir"
      - "directory.stat.mode == '0755'"
      - "directory.stat.pw_name == 'root'"
      - "directory.stat.gr_name == 'root'"

- name: "Get stat on Intellij application menu entry"
  stat:
    path: "/usr/share/applications/{{ intellij_desktop_filename }}"
  register: file

- name: "Assert that Intellij application menu entry is present"
  assert:
    that:
      - "file.stat.exists"
